### PR TITLE
add dev env to work with

### PR DESCRIPTION
**Pull request by KathleenA**
- added index.html to have a dev environment to work with
- added package [lite-server](https://www.npmjs.com/package/lite-server) to start local server for index.html
- yarn vendor files are added

This is a separat PR because of the huge amount of vendor files.

I use the same environment for endcard and it's working very well.

### CODE REVIEW

**Review by Tungse — APPROVED** [review]
Ich habe mir alle 337 Dateien genau angeschaut, und das alles sieht für mich gut aus.

**Review by jrsmb — APPROVED** [review]

**Comment by Tungse** [comment]
@KathleenA ist there a `data-endscreen-revolverplay-timeout="SEC_VALUE"` feature?

**Comment by KathleenA** [comment]
> @KathleenA ist there a `data-endscreen-revolverplay-timeout="SEC_VALUE"` feature?

No. Revolverplay time can be set in endcard options https://github.com/stroeer/stroeer-videoplayer-plugin-endcard#revolverplaytime---number

**Comment by KathleenA** [comment]
@walialu Is this ok for you? :)

**Review by walialu — APPROVED** [review]
Ja, klar, sieht gut aus :)

**Pull request merged**
